# SPDX-FileCopyrightText: 2021-2025 Mikhail Rachinskiy
# SPDX-License-Identifier: GPL-3.0-or-later

import json
from collections.abc import Iterator
from pathlib import Path


def _po_parse(text: str) -> dict[tuple[str, str], str]:
    import re
    concat_multiline = text.replace('"\n"', "")
    entries = re.findall(r'(?:msgctxt\s*"(.+)")?\s*msgid\s*"(.+)"\s*msgstr\s*"(.*)"', concat_multiline)

    return {
        (ctxt or "*", key.replace("\\n", "\n")): msg.replace("\\n", "\n")
        for ctxt, key, msg in entries
        if msg
    }


def _walk() -> Iterator[tuple[str, dict[tuple[str, str], str]]]:
    for child in Path(__file__).parent.iterdir():
        if child.is_file() and child.suffix == ".po":
            with open(child, "r", encoding="utf-8") as file:
                yield child.stem, _po_parse(file.read())


def _init() -> dict[str, dict[tuple[str, str], str]]:
    path = Path(__file__).parent / "__cache__.json"

    if path.exists():
        with open(path, "r", encoding="utf-8") as file:
            data = json.load(file)
            
            # JSON keys are strings, convert back stringified tuples "('context', 'key')" to proper tuple keys
            parsed_dictionary = {}
            for locale, trnsl in data.items():
                parsed_trnsl = {}
                for key_str, msg in trnsl.items():
                    # Parse "('context', 'key')" back to tuple
                    # The literal_eval is safe here because we only parse tuples of strings generated by this same module
                    import ast
                    try:
                        key_tuple = ast.literal_eval(key_str)
                        if isinstance(key_tuple, tuple):
                            parsed_trnsl[key_tuple] = msg
                    except (ValueError, SyntaxError):
                        continue
                parsed_dictionary[locale] = parsed_trnsl
                
            return parsed_dictionary

    dictionary = {locale: trnsl for locale, trnsl in _walk()}
    
    # Pre-parse dictionary keys from tuple to str for JSON serialization
    json_dictionary = {}
    for locale, trnsl in dictionary.items():
        json_dictionary[locale] = {str(k): v for k, v in trnsl.items()}

    with open(path, "w", encoding="utf-8") as file:
        json.dump(json_dictionary, file, ensure_ascii=False)

    return dictionary


DICTIONARY = _init()
